# Generated by Django 3.2.18 on 2023-08-29 15:09

import django.db.models.deletion
from django.db import migrations, models

import pgvector.django
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="TettraPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("page_title", models.CharField(max_length=255)),
                ("owner_id", models.IntegerField()),
                ("owner_name", models.CharField(max_length=255)),
                ("owner_email", models.EmailField(max_length=254)),
                ("url", models.URLField()),
                ("html", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TettraPageCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category_id", models.BigIntegerField(db_index=True, unique=True)),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TettraPageSubcategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subcategory_id", models.BigIntegerField(db_index=True, unique=True)),
                ("subcategory_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TettraPageChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", pgvector.django.VectorField(blank=True, dimensions=384, null=True)),
                (
                    "tettra_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="tettra.tettrapage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tettrapage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tettra_pages",
                to="tettra.tettrapagecategory",
            ),
        ),
        migrations.AddField(
            model_name="tettrapage",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tettra_pages",
                to="tettra.tettrapagesubcategory",
            ),
        ),
    ]
