# Generated by Django 3.2.18 on 2023-12-13 07:52

from django.db import migrations

import apps.tettra.models


class Migration(migrations.Migration):

    dependencies = [
        ("tettra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tettrapagesubcategory",
            name="subcategory_icon",
            field=apps.tettra.models.EmojiField(blank=True, max_length=10, null=True),
        ),
    ]
