# Generated by Django 3.2.18 on 2023-07-20 15:38

import django.db.models.deletion
from django.db import migrations, models

import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("tettra", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tettrapage",
            name="embedding",
        ),
        migrations.CreateModel(
            name="TettraPageChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", pgvector.django.VectorField(blank=True, dimensions=384, null=True)),
                (
                    "tettra_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="tettra.tettrapage",
                    ),
                ),
            ],
        ),
    ]
