# Generated by Django 3.2.18 on 2023-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tettra", "0002_auto_20230720_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tettrapage",
            name="subcategory_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tettrapage",
            name="subcategory_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
