# Generated by Django 3.2.18 on 2023-07-27 15:56

from django.db import migrations


def _delete_tettra_page_chunks(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    TettraPageChunk = apps.get_model("tettra", "TettraPageChunk")

    TettraPageChunk.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tettra", "0003_auto_20230727_1556"),
    ]

    operations = [
        migrations.RunPython(
            _delete_tettra_page_chunks, reverse_code=migrations.RunPython.noop, atomic=True
        ),
    ]
