image: silverlogic/python3.5

pipelines:
  default:
    - step:
        script:
          - pyvenv venv
          - source venv/bin/activate
          - pip install -r requirements/dev.txt

          - flake8
          - if [ $(isort **/*.py --diff -q | wc -l) -gt 0 ]; then echo "Sort your imports and commit again."; (exit 1); fi

          - export SECRET_KEY=notsecret
          - export DATABASE_URL='postgis://postgres:postgres@localhost/pipelines'
          - export CELERY_BROKER_URL="N/A"
          - export URL="http://localhost"
          - export FRONT_URL="http://app.localhost"
          - export BRANCHIO_KEY="key_test_pmEf8Pqmg05t4N1MamZw4egeyxahRfTj"
          - py.test --cov="apps" tests

          - pip install codecov
          - codecov --token="17ec662a-faa2-4c69-b2ba-e272bf81e0a4"

          - test "$BITBUCKET_BRANCH" = master && curl -XPOST "https://ops.tsl.io/api/17/job/$RUNDECK_STAGING_JOB_ID/executions?authtoken=6m5rvQR1JFY8r43WtZkKkvQyKtjQIisl" || true  # Deploy staging api
          - test "$BITBUCKET_BRANCH" = master && curl -XPOST "https://ops.tsl.io/api/17/job/$RUNDECK_STAGING_DOCS_JOB_ID/executions?authtoken=6m5rvQR1JFY8r43WtZkKkvQyKtjQIisl" || true  # Deploy staging apidocs
          - test "$BITBUCKET_BRANCH" = production && curl -XPOST "https://ops.tsl.io/api/17/job/$RUNDECK_PRODUCTION_JOB_ID/executions?authtoken=6m5rvQR1JFY8r43WtZkKkvQyKtjQIisl" || true  # Deploy production api
        services:
          - database
definitions:
  services:
    database:
      image: silverlogic/postgres9.6
