# Generated by Django 3.2.18 on 2023-06-19 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIChat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4", "gpt-4"),
                            ("gpt-3.5-turbo-16k", "gpt-3.5-turbo-16k"),
                            ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                            ("gpt-4-0613", "gpt-4-0613"),
                            ("gpt-4-0314", "gpt-4-0314"),
                        ],
                        default="gpt-4",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenAIChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("user", "user"),
                            ("assistant", "assistant"),
                        ],
                        max_length=9,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.openaichat",
                    ),
                ),
            ],
        ),
    ]
