# Generated by Django 3.2.18 on 2023-08-29 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tettra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIChat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4", "gpt-4"),
                            ("gpt-3.5-turbo-16k", "gpt-3.5-turbo-16k"),
                            ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                            ("gpt-4-0613", "gpt-4-0613"),
                            ("gpt-4-0314", "gpt-4-0314"),
                        ],
                        default="gpt-4",
                        max_length=20,
                    ),
                ),
                (
                    "tettra_page_category_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openai_chats",
                        to="tettra.tettrapagecategory",
                    ),
                ),
                (
                    "tettra_page_subcategory_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openai_chats",
                        to="tettra.tettrapagesubcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpenAIChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("user", "user"),
                            ("assistant", "assistant"),
                        ],
                        max_length=9,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("thumbs_up", "thumbs_up"),
                            ("thumbs_down", "thumbs_down"),
                        ],
                        default="none",
                        max_length=11,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.openaichat",
                    ),
                ),
                (
                    "tettra_page_chunks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Similar tettra page chunks to the content of this message.",
                        related_name="tettra_page_chunks",
                        to="tettra.TettraPageChunk",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
