# Generated by Django 3.2.18 on 2023-06-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tettra", "0001_initial"),
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaichatmessage",
            name="tettra_pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Similar tettra pages to the content of this message.",
                related_name="tettra_pages",
                to="tettra.TettraPage",
            ),
        ),
    ]
