# Generated by Django 4.2.11 on 2025-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_auto_20230914_1335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaichat",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o", "gpt-4o"),
                    ("chatgpt-4o-latest", "chatgpt-4o-latest"),
                    ("o1", "o1"),
                    ("o1-mini", "o1-mini"),
                ],
                default="gpt-4o",
                max_length=20,
            ),
        ),
    ]
