# Generated by Django 3.2.18 on 2023-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tettra", "0002_auto_20230720_1538"),
        ("chatbot", "0002_openaichatmessage_tettra_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openaichatmessage",
            name="tettra_pages",
        ),
        migrations.AddField(
            model_name="openaichatmessage",
            name="tettra_page_chunks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Similar tettra page chunks to the content of this message.",
                related_name="tettra_page_chunks",
                to="tettra.TettraPageChunk",
            ),
        ),
    ]
