# Generated by Django 3.2.18 on 2023-07-24 18:09

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_auto_20230724_0258"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaichat",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="openaichat",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="openaichatmessage",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="openaichatmessage",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="openaichatmessage",
            name="rating",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("thumbs_up", "thumbs_up"),
                    ("thumbs_down", "thumbs_down"),
                ],
                default="none",
                max_length=11,
            ),
        ),
    ]
