# Generated by Django 4.2.11 on 2025-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_alter_openaichat_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaichat",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("chatgpt-4o-latest", "chatgpt-4o-latest"),
                    ("o1", "o1"),
                    ("o1-mini", "o1-mini"),
                ],
                default="gpt-4o-mini",
                max_length=20,
            ),
        ),
    ]
