# Generated by Django 3.2.15 on 2022-08-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(blank=True, max_length=100),
        ),
    ]
